version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:21.6.2-browsers
    working_directory: ~/repo
    environment:
      GIT_AUTHOR_EMAIL: visjsbot@gmail.com
      GIT_AUTHOR_NAME: vis-bot
      GIT_COMMITTER_EMAIL: visjsbot@gmail.com
      GIT_COMMITTER_NAME: vis-bot

jobs:
  prepare:
    executor: node

    steps:
      - checkout

      - run: npm ci

      - persist_to_workspace:
          root: .
          paths:
            - "*"

  build:
    executor: node

    steps:
      - attach_workspace:
          at: .

      - run: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - "declarations"
            - "dist"
            - "esnext"
            - "peer"
            - "standalone"
            - "styles"
            - "types"

  examples:
    executor: node

    steps:
      - attach_workspace:
          at: .

      - run: npm run generate-examples-index

      - persist_to_workspace:
          root: .
          paths:
            - "examples"

  lint:
    executor: node

    steps:
      - attach_workspace:
          at: .

      - run: npm run lint

  test:
    executor: node

    steps:
      - attach_workspace:
          at: .

      - run: npm run test-cov

  release:
    executor: node

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Prepare NPM
          command: |
            npm set //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}

      - run:
          name: Release
          command: |
            npx semantic-release

workflows:
  version: 2

  build:
    jobs:
      - prepare

      - build:
          requires:
            - prepare

      - examples:
          requires:
            - prepare
            - build

      # Enable when the code base is ready.
      # - lint:
      #     requires:
      #       - prepare

      - test:
          requires:
            - prepare
            - build

      - release:
          requires:
            - prepare
            - build
            - examples
            # - lint
            - test
          filters:
            branches:
              only:
                - master
